drop table if exists tb_cartorio;
drop table if exists tb_certidao;
create table tb_cartorio (id int8 generated by default as identity, nome varchar(255), logradouro varchar(255), certidao_id int8, primary key (id));
create table tb_certidao (id int8, nome varchar(255), primary key (id));
alter table if exists tb_cartorio add foreign key (certidao_id) references tb_certidao;





